### ISSUE TITLE
Sprint-12/New-screen-for-your-reservation-details.

### ISSUE THREAD

**Issue by AxeLoza21** [BrightCoders-Institute/s8pf-team-05#114]
## REQUIREMENTS / DESCRIPTION

Create a new screen that displays your complete reservation information when you click on a reservation in the Trips screen.

## TASK

- [ ] Make the design of the new screen.
- [ ] Add the functionality to your reservations in the Trips screen to redirect you to the new screen, passing all the information to them.
- [ ] Realize the functionality of the new screen
