### ISSUE TITLE
Implement Navigation

### ISSUE THREAD

**Issue by martinmt-mx** [BrightCoders-Institute/s8pf-team-05#3]
## REQUIREMENTS / DESCRIPTION

> Set up basic navigation between screens/pages.

## TASKS

- [ ] Install a navigation library (e.g., React Navigation).
- [ ] Create navigation components for navigating between different screens.
- [ ] Implement navigation logic to switch between screens.
