### ISSUE TITLE
Sprint-10/Fix-bugs

### ISSUE THREAD

**Issue by Diana-Camz** [BrightCoders-Institute/s8pf-team-05#93]
## REQUIREMENTS / DESCRIPTION

> There are some details or arrangements that have to be made on different screens so that the application works according to how we want.

## TASKS

- [x] Quitar Select Availability Dates y modificar el campo de Select City de Editar. 
- [x] cambiar el boton de Edit Property para que no se stackeen las pantallas.
- [x] si te logeas con Google que te mande a Select City.
- [x] si te logeas con Google que te permita ser Host.
- [x] cuando te conviertes en Host debe de mostrarse en Perfil.
- [x] propiedades duplicadas en Explore.
- [x] Scroll en tus reservaciones.
- [x] editar la fecha en el Confirmation Screen.
- [x] quitar el boton de loguearse con Facebook.
- [x] En la pantalla de explore cambiar la ciudad por el titulo de la propiedad.
- [x] cambiar logo de "other" del scroll de los tipos de propiedades.
